# Generated by Django 4.2.1 on 2023-06-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=100)),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horsepower', models.PositiveIntegerField()),
                ('torque', models.PositiveIntegerField()),
                ('zero_to_sixty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quarter_mile_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('engine_configuration', models.CharField(choices=[('inline', 'Inline'), ('v', 'V'), ('flat', 'Flat'), ('w', 'W'), ('rotary', 'Rotary')], default='inline', max_length=100)),
                ('cylinders', models.PositiveIntegerField()),
                ('drivetrain', models.CharField(choices=[('fwd', 'Front Wheel Drive'), ('rwd', 'Rear Wheel Drive'), ('awd', 'All Wheel Drive')], default='fwd', max_length=100)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'Continuously Variable Transmission')], default='manual', max_length=100)),
                ('range', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
        ),
    ]
